title: Statistics
description: Data-driven statistics based on open Profixio data sources.
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

show_downloads: false
github:
  is_project_page: false

# Exclude these from Jekyll processing
exclude:
  - cache/
